FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY dashboard.py .
COPY utils.py .
COPY constants.py .

# Exposition du port utilisé par Streamlit
EXPOSE 8501

# Configuration des variables d'environnement pour Streamlit
ENV STREAMLIT_SERVER_PORT=8501
ENV STREAMLIT_SERVER_HEADLESS=true
ENV STREAMLIT_SERVER_ENABLE_CORS=false

# Lancement de l'application
CMD ["streamlit", "run", "dashboard.py"] 